[package]
name = "simple-server-engine-web-consumer"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
simple-server = { package = "lelloman-simple-server", path = "../../..", default-features = false, features = ["engine-web", "client"] }
serde_json = "1"
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
